/**/

CREATE OR REPLACE VIEW vw_team AS

SELECT
    ts.id,
    ts.match_id,
    ts.team_id,
    m.start_time AS match_start_time,
    m.duration AS match_duration,
    m.lifecycle_mode,
    m.game_variant_category,
    m.map_variant,
    m.game_variant,
    m.playlist,
    m.playlist_experience,
    m.map_mode_pair,
    o.name AS outcome,
    ts.rank,
    ts.score,
    ts.personal_score,
    ts.rounds_won,
    ts.rounds_lost,
    ts.rounds_tied,
    ts.kills,
    ts.deaths,
    ts.assists,
    ts.suicides,
    ts.betrayals,
    ts.grenade_kills,
    ts.headshot_kills,
    ts.melee_kills,
    ts.power_weapon_kills,
    ts.shots_fired,
    ts.shots_hit,
    ts.damage_dealt,
    ts.damage_taken,
    ts.callout_assists,
    ts.driver_assists,
    ts.emp_assists,
    ts.vehicle_destroys,
    ts.hijacks,
    ts.max_killing_spree,
    tsk.mmr,
    avg(psk.pre_match_csr) AS pre_match_csr,
    avg(psk.post_match_csr) AS post_match_csr,
    sum(psk.kills_expected) AS kills_expected,
    sum(psk.deaths_expected) AS deaths_expected
FROM team_stat ts
JOIN vw_match m ON ts.match_id = m.id
JOIN outcome o ON ts.outcome_id = o.id
LEFT JOIN team_skill tsk ON ts.match_id = tsk.match_id AND ts.team_id = tsk.team_id
LEFT JOIN player_skill psk ON ts.match_id = psk.match_id AND ts.team_id = psk.team_id
GROUP BY
    ts.id,
    ts.match_id,
    ts.team_id,
    m.start_time,
    m.duration,
    m.lifecycle_mode,
    m.game_variant_category,
    m.map_variant,
    m.game_variant,
    m.playlist,
    m.playlist_experience,
    m.map_mode_pair,
    o.name,
    ts.rank,
    ts.score,
    ts.personal_score,
    ts.rounds_won,
    ts.rounds_lost,
    ts.rounds_tied,
    ts.kills,
    ts.deaths,
    ts.assists,
    ts.suicides,
    ts.betrayals,
    ts.grenade_kills,
    ts.headshot_kills,
    ts.melee_kills,
    ts.power_weapon_kills,
    ts.shots_fired,
    ts.shots_hit,
    ts.damage_dealt,
    ts.damage_taken,
    ts.callout_assists,
    ts.driver_assists,
    ts.emp_assists,
    ts.vehicle_destroys,
    ts.hijacks,
    ts.max_killing_spree,
    tsk.mmr